### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghost** [HarukaKinen/Sinmai-Internal-Damage#3]
无

**Comment by 2235464807** [comment]
> 未经处理的异常: SharpMonoInjector.InjectorException: Failed to open process ---> System.ComponentModel.Win32Exception: 拒绝访问。 --- 内部异常堆栈跟踪的结尾 --- 在 SharpMonoInjector.Injector..ctor(String processName) 在 SharpMonoInjector.Console.Program.Main(String[] args)

- [ ] ### 
/ #
